### ISSUE TITLE
ASAR function naming conventions

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-ost/asar#12]
@Schiano-NOAA requests a review of the [ASAR function names](https://github.com/Schiano-NOAA/ASAR/tree/main/R) to ensure they make sense.  I have a few non-blocking suggestions and questions below. 

- Use verbs for function names following the [Tidyverse style guide](https://style.tidyverse.org/functions.html?q=verb#naming). This could apply to following functions:
    - Modify `report_format.R` to `format_report.R`
    - Modify  `chunkr.R` to `add_code_chunk.R`
    - Modify  `afsc_tier_table.R` to `create_afsc_tier_table.R`.
- Use prefixes to distinguish some functions:
    - I am not sure about the difference between add_theme.R, create_style_css.R, and report_format.R. Are they all styling functions for different parts of the report? Could we use names like `style_figure_and_table.R`. `style_title.R`, and `style_report.R`?
    - Another way to categorize the functions would be to add parts of the report to the name of the file. For example, `title_write.R`, `title_style.R`, `report_add_section.R`, `report_style.R`, `report_export_object.R`, `assessment_convert_output.R`. See examples from {[ggplot2](https://github.com/tidyverse/ggplot2/tree/main/R)} and {[dplyr](https://github.com/tidyverse/dplyr/tree/main/R)}. I am not sure which approach works better here.
-  `util.R` is an empty file, maybe just remove it from the repo for now?

It's exciting to see so many functions in the repo already! 🥳

**Comment by Schiano-NOAA** [comment]
I have made changes to the naming conventions of many of the current functions in the package. I am going to keep this open for any future naming convention conversations that may continue or for deciding among names for new functions.
