### ISSUE TITLE
skeleton numbering

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [nmfs-ost/asar#25]
i would encourage numbering the skeleton files e.g., `01-exec_summary.qmd`, `02-introduction`, etc., it facilitates keeping things in line particularly as file systems increase in size

**Comment by Schiano-NOAA** [comment]
@Bai-Li-NOAA I am planning on both restructuring the stock assessment report sections to mimic those we talked about in the steering committee meeting back in August as well as add numbering. I won't be doing this till next week; however when this occurs, a few of the tests will fail in the package. I will flag you when I perform that pull request, but I wanted to make you aware.

**Comment by Bai-Li-NOAA** [comment]
@Schiano-NOAA, thanks for the heads-up! It would be great to pause development on the main branch before the Library Seminar to make sure it's ready for the demo. Feel free to update the tests during development, and I’m happy to jump in as a reviewer on the pull request when you’re ready.

**Comment by Schiano-NOAA** [comment]
Great! That's the plan. I had to make a small change to the example in the README but you'll be able to find further changed in the 'dev' branch. Sophie and I will be only using that one moving forward until it is prepared for another beta release.

**Comment by Schiano-NOAA** [comment]
Numbering in the skeleton was performed and added into the development branch. These changes will be reflected in the next beta release
