### ISSUE TITLE
AFSC-ABL

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [nmfs-ost/asar#26]
https://github.com/nmfs-ost/asar/blob/c1b3e8017b75aa0a9441fab0f61afc78419f7a2d/inst/resources/affiliation_info.csv#L20

Slightly different from the format you are using here, but the Juneau office is typically designated as ABL (Auke Bay Laboratories)
So maybe AFSC-ABL instead of (or in addition to) AFSC-JAK?

**Comment by Schiano-NOAA** [comment]
Thanks for letting me know Ben! I made it an option so its following both the naming convention with the other labs in addition to the typical lab name for the center.
