### ISSUE TITLE
[Question]: New folders created from recent PR

### ISSUE THREAD

**Issue by Schiano-NOAA** [nmfs-ost/asar#67]
### What is your question?

Do we need the doc and Meta folders?

### Additional context

@sbreitbart-NOAA I noticed that these folders were made. The doc folder is not necessary because the compiled HTMLs for each vignette are contained in the gh-pages branch. Additionally, what is loaded in from the Meta folder? Can we reference and move it somewhere else.

If any of these folders are necessary, please let me know, but I am suggesting we delete them.

**Comment by sbreitbart-NOAA** [comment]
Hey @Schiano-NOAA - I don't think any of these files are necessary. I believe they were created when I entered a devtools command to check the project, or build the project's documentation.

**Comment by Schiano-NOAA** [comment]
I've never had it build during devtools::check. You can use pkgdown::build_site to test it out. I'm going to delete the files for a second locally and see if it remakes them

**Comment by Schiano-NOAA** [comment]
@sbreitbart-NOAA I've never had it build during devtools::check. You can use pkgdown::build_site to test it out. I'm going to delete the files for a second locally and see if it remakes them
