### ISSUE TITLE
 Ubuntu in cmd check failing

### ISSUE THREAD

**Issue by Schiano-NOAA** [nmfs-ost/asar#73]
@Bai-Li-NOAA This particular check for each branch is failing. I haven't yet encountered this type of issue. Do you have any knowledge of this issue or what is causing it?
[Here](https://github.com/nmfs-ost/asar/actions/runs/11630365830) is the action and this is the error it's throwing
`Warning: Input 'save-always' has been deprecated with message: save-always does not work as intended and will be removed in a future release.`

**Comment by Schiano-NOAA** [comment]
@Bai-Li-NOAA Great thanks so much for the advice!

**Comment by Bai-Li-NOAA** [comment]
@Schiano-NOAA, I re-ran the failed GHA workflow, and it [passed](https://github.com/nmfs-ost/asar/actions/runs/11630365830)! 🎉 Feel free to re-run any other failed workflows if needed. 


![Capture](https://github.com/user-attachments/assets/73b83873-4d34-488d-87be-db96dad4e967)
