### ISSUE TITLE
[Bug]: Default skeleton fails to render

### ISSUE THREAD

**Issue by Schiano-NOAA** [nmfs-ost/asar#83]
### Describe the bug

When rendering from blank after creating the template (AKA default), the compilation fails producing error

`compilation failed- error Paragraph ended before \Gin@iii was complete. <to be read again>  \par  l.267 `

### Describe how to reproduce the bug

asar:create_template()

### Which OS are you seeing the problem on?

Windows

### Which version of asar are you seeing the problem on?

main branch - current version

**Comment by sbreitbart-NOAA** [comment]
Fixed: https://github.com/nmfs-ost/asar/commit/2a4766d10425c6ef32d44f34988a49f8bf1a5576
