### ISSUE TITLE
[Bug]: vignette not display as intended

### ISSUE THREAD

**Issue by Schiano-NOAA** [nmfs-ost/asar#93]
### Describe the bug

The following code chunk in the vignette will not be displayed as intended to the user:

https://github.com/nmfs-ost/asar/blob/a9b19fec03254fa533b7408c93f7b0078835adf8/vignettes/accessibility_guide.Rmd#L44-L46

### Which OS are you seeing the problem on?

Windows

### Which version of asar are you seeing the problem on?

dev branch

**Comment by sbreitbart-NOAA** [comment]
PR to fix bug: https://github.com/nmfs-ost/asar/pull/95

**Comment by sbreitbart-NOAA** [comment]
Closed as completed.
